apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argodemo
  template:
    metadata:
      name: argo-pod
      labels:
        app: argodemo
    spec:
      containers:
      - name: argo-container
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080        
